config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  devise_for :admins, controllers: {
      sessions: 'admins/sessions',
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  get 'auth/failure', :to => 'session#failure'
  resources :users

  namespace :admins do
    root "users#index"
    resources :users
    end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/social.rb
class Social < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :provider, presence: true
  validates :uid, presence: true

  # def self.new_with_session(params, session)
  #   super.tap do |user|
  #     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
  #       user.email = data["email"] if user.email.blank?
  #     end
  #   end
  # end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |social|
      social.provider= auth.provider
      social.uid= auth.uid
      social.save!
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :avatar, AvatarUploader
  serialize :avatars, JSON
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable, omniauth_providers: [:facebook, :google_oauth2]
  validates_integrity_of  :avatar
  validates_processing_of :avatar
  has_many :socials, dependent: :destroy
  ATTRIBUTES_PARAMS = [:email, :name, :password, :password_confirmation, :dob, :avatar]

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end

end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    # session[:admin]= current_admin
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end


  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end

  def after_sign_in_path_for(resource)
    admins_users_path
  end

  # def current_admin
  #
  #   @current_admin ||= warden.authenticate(:scope => :admin)
  # end
  end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController

  before_action :authenticate_admin!, only: [:index, :new]
  def index
    @users= User.paginate(page: params[:page])
  end

  def new
    @user= User.new
  end

  def create
    @user= User.new user_params
    if @user.save
      flash[:success] = "User created!"
      redirect_to admins_users_path
    else
      render :new
    end
  end


  private
  def user_params
    params.require(:user).permit User::ATTRIBUTES_PARAMS
  end
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  def show
    @admin= Admin.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  respond_to :html, :json
  before_action :configure_permitted_parameters, if: :devise_controller?

  def get_module_name
    @module_name = self.class.name.split("::").first
  end
  protected
  def configure_permitted_parameters
    added_attrs = [:email, :password, :password_confirmation, :remember_me, :name, :dob, :avatar, :id]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/socials_controller.rb
class SocialsController < ApplicationController

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create, :edit, :new]
  before_action :authenticate_user!, only: [:edit]


  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to admins_users_path
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit User::ATTRIBUTES_PARAMS
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title page_title = ""
    base_title = t "base_title"
    page_title.empty? ? base_title : page_title + " | " + base_title
  end
  def admin?
    controller.class.name.split("::").first=="Admin"
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/socials_helper.rb
module SocialsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
              <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
              <li><%= link_to "Users Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pr1Rktt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">

    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>

  </div>

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
  <p class="navbar-text pull-right">

        <% if current_user %>
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
        <%= link_to "UsersLogout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
        <%= link_to 'Profile',  current_user %>

    <% elsif current_admin %>
        <%= link_to 'Admin Logout',  destroy_admin_session_path, method: :delete, :class => 'navbar-link' %>
        <%= link_to 'Users',  users_path %>
    <% end %>
  </p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>The first project</p>